[helpers]

[default]
depends = []

[default.files]
"hyprland.conf" = "~/.config/hypr/hyprland.conf"
"waybar/config" = "~/.config/waybar/config"
"waybar/style.css" = "~/.config/waybar/style.css"
"dunstrc" = "~/.config/dunst/dunstrc"
"swaylock_config" = "~/.config/swaylock/config"
"starship.toml" = "~/.config/starship.toml"
".bashrc" = "~/.bashrc"
".profile" = "~/.profile"
".gitconfig" = "~/.gitconfig"
"gitignore" = "~/.gitignore"
"vscode/settings.json" = "~/.config/Code/User/settings.json"
"vscode/keybindings.json" = "~/.config/Code/User/keybindings.json"
"ripgreprc" = "~/.ripgreprc"
"alacritty.toml" = "~/.config/alacritty/alacritty.toml"
".tmux.conf" = "~/.tmux.conf"
"bin/frg.sh" = "~/bin/frg"
"bin/clg.sh" = { target = "~/bin/clg", type = "symbolic" }

[default.variables]
